# MiniProject Wine

Citation Request:
  This dataset is public available for research. The details are described in [Cortez et al., 2009].
  Please include this citation if you plan to use this database:

  P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
  Modeling wine preferences by data mining from physicochemical properties.
  In Decision Support Systems, Elsevier, 47(4):547-553. ISSN: 0167-9236.

  Available at: [@Elsevier] http://dx.doi.org/10.1016/j.dss.2009.05.016
                [Pre-press (pdf)] http://www3.dsi.uminho.pt/pcortez/winequality09.pdf
                [bib] http://www3.dsi.uminho.pt/pcortez/dss09.bib

1. Title: Wine Quality

2. Sources
   Created by: Paulo Cortez (Univ. Minho), Antonio Cerdeira, Fernando Almeida, Telmo Matos and Jose Reis (CVRVV) @ 2009
   
3. Past Usage:

  P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
  Modeling wine preferences by data mining from physicochemical properties.
  In Decision Support Systems, Elsevier, 47(4):547-553. ISSN: 0167-9236.

  In the above reference, two datasets were created, using red and white wine samples.
  The inputs include objective tests (e.g. PH values) and the output is based on sensory data
  (median of at least 3 evaluations made by wine experts). Each expert graded the wine quality
  between 0 (very bad) and 10 (very excellent). Several data mining methods were applied to model
  these datasets under a regression approach. The support vector machine model achieved the
  best results. Several metrics were computed: MAD, confusion matrix for a fixed error tolerance (T),
  etc. Also, we plot the relative importances of the input variables (as measured by a sensitivity
  analysis procedure).

4. Relevant Information:

   The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine.
   For more details, consult: http://www.vinhoverde.pt/en/ or the reference [Cortez et al., 2009].
   Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables
   are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).

   These datasets can be viewed as classification or regression tasks.
   The classes are ordered and not balanced (e.g. there are munch more normal wines than
   excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent
   or poor wines. Also, we are not sure if all input variables are relevant. So
   it could be interesting to test feature selection methods.

5. Number of Instances: red wine - 1599; white wine - 4898.

6. Number of Attributes: 11 + output attribute
  
   Note: several of the attributes may be correlated, thus it makes sense to apply some sort of
   feature selection.

7. Attribute information:

   For more information, read [Cortez et al., 2009].

   Input variables (based on physicochemical tests):
   1 - fixed acidity
   2 - volatile acidity
   3 - citric acid
   4 - residual sugar
   5 - chlorides
   6 - free sulfur dioxide
   7 - total sulfur dioxide
   8 - density
   9 - pH
   10 - sulphates
   11 - alcohol
   Output variable (based on sensory data):
   12 - quality (score between 0 and 10)

8. Missing Attribute Values: None

In [2]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
wine_df = pd.read_csv("https://raw.githubusercontent.com/fisicangel/Min-project-2-wine/main/winequality-white.csv", sep=";")
wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

**Check the shape of your data**

In [4]:
wine_df.shape

(4898, 12)

**Check for data types**

In [5]:
wine_df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

**Check for missing values**

In [6]:
wine_df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [7]:
wine_df.duplicated().sum()

np.int64(937)

In [8]:
#dropping rows with missing values and renaming the data frame
# Opcion 1
wine_df.drop_duplicates(inplace=True)
display(wine_df.head())
display(wine_df.shape)
# Opcion 2
# df = wine_df.drop_duplicates()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6

(3961, 12)

In [9]:
#wine_df.describe()
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3961 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         3961 non-null   float64
 1   volatile acidity      3961 non-null   float64
 2   citric acid           3961 non-null   float64
 3   residual sugar        3961 non-null   float64
 4   chlorides             3961 non-null   float64
 5   free sulfur dioxide   3961 non-null   float64
 6   total sulfur dioxide  3961 non-null   float64
 7   density               3961 non-null   float64
 8   pH                    3961 non-null   float64
 9   sulphates             3961 non-null   float64
 10  alcohol               3961 non-null   float64
 11  quality               3961 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 402.3 KB

**KNN**

K Nearest Neighbors is a distance based algorithm, and requeries all **input data to be numerical.**

Let's only select numerical columns as our features.

In [10]:
wine_df.keys()

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [11]:
#all columns are numerical
#Selecting the target
target = wine_df['quality']
features = wine_df.drop(columns = ["quality"])
display(features.head())
display(features.shape)
display(target.head())
display(target.shape)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.9949,3.18,0.47,9.6

(3961, 11)

0    6
1    6
2    6
3    6
6    6
Name: quality, dtype: int64

(3961,)

And also lets define our target.

In [12]:
wine_df['quality'].value_counts()

quality
6    1788
5    1175
7     689
4     153
8     131
3      20
9       5
Name: count, dtype: int64

**Train Test Split**

Now that we have split the data into **features** and **target** variables and imported the **train_test_split** function, split X and y into X_train, X_test, y_train, and y_test. 80% of the data should be in the training set and 20% in the test set.

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, stratify= target, test_size=0.20, random_state=0)

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

You need to choose between **Classificator** or **Regressor**. Take into consideration target variable to decide.

Initialize a KNN instance without setting any hyperparameter.

In [14]:
from sklearn.neighbors import KNeighborsClassifier

Fit the model to your data.

In [15]:
knn = KNeighborsClassifier(n_neighbors=3) # n_neighbors = K

In [16]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [17]:
pred = knn.predict(X_test) # vs y_test
pred

array([6, 7, 6, 6, 6, 6, 5, 6, 4, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5,
       5, 7, 6, 6, 5, 4, 6, 5, 5, 6, 5, 5, 7, 5, 5, 6, 6, 6, 7, 6, 3, 5,
       6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 7,
       7, 5, 5, 4, 5, 6, 6, 5, 7, 6, 6, 5, 5, 7, 5, 6, 6, 6, 7, 5, 6, 6,
       6, 7, 5, 5, 7, 6, 5, 7, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 5, 6,
       5, 6, 6, 5, 6, 4, 6, 6, 6, 6, 6, 6, 7, 6, 5, 6, 7, 4, 6, 5, 7, 6,
       6, 6, 6, 6, 4, 5, 5, 7, 7, 6, 6, 5, 5, 5, 6, 4, 5, 6, 7, 5, 5, 6,
       6, 5, 5, 5, 5, 6, 6, 5, 4, 6, 6, 6, 5, 5, 7, 6, 7, 5, 5, 7, 5, 5,
       6, 6, 6, 5, 6, 4, 5, 6, 5, 5, 6, 5, 5, 4, 7, 6, 5, 6, 6, 7, 6, 6,
       6, 7, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 7, 6, 6, 6,
       6, 5, 6, 6, 7, 4, 5, 6, 7, 6, 4, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 7,
       7, 6, 5, 7, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 5, 5, 5, 7, 6, 6, 5, 6, 7, 6, 6, 7, 4, 6, 5, 5, 5,
       5, 6, 6, 5, 5, 6, 6, 6, 5, 5, 7, 7, 6, 6, 8, 6, 7, 6, 6, 6, 6, 5,
       6, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 6, 7, 5, 5, 7, 6, 6, 6, 6, 7,
       5, 5, 6, 6, 6, 6, 6, 6, 5, 4, 7, 6, 5, 6, 6, 6, 5, 6, 5, 7, 6, 6,
       5, 6, 5, 6, 6, 7, 5, 7, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 4,
       7, 6, 6, 5, 6, 4, 4, 6, 6, 6, 6, 6, 5, 6, 7, 4, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 4, 7, 5, 5, 6, 5, 4, 6, 5, 6, 6, 6, 7, 6, 6, 6, 5, 6, 6,
       5, 6, 6, 5, 6, 5, 4, 6, 7, 7, 4, 6, 7, 5, 5, 5, 5, 6, 5, 6, 5, 5,
       5, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 7, 6,
       6, 6, 5, 6, 6, 7, 6, 7, 5, 6, 5, 6, 5, 4, 6, 4, 6, 5, 5, 5, 7, 6,
       6, 6, 6, 6, 6, 7, 7, 6, 7, 5, 6, 7, 6, 6, 6, 6, 5, 6, 5, 6, 6, 4,
       7, 7, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 4, 6, 6, 6, 5, 7, 5, 6,
       5, 5, 6, 5, 6, 6, 7, 7, 5, 6, 6, 5, 5, 6, 5, 6, 4, 6, 6, 6, 7, 7,
       7, 6, 6, 6, 5, 6, 6, 6, 6, 6, 4, 5, 6, 5, 5, 5, 7, 6, 6, 7, 5, 6,
       6, 6, 6, 6, 6, 7, 5, 6, 5, 5, 5, 5, 3, 5, 7, 6, 5, 6, 5, 7, 6, 5,
       7, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6, 6, 5,
       6, 6, 6, 6, 6, 7, 5, 5, 6, 5, 7, 5, 6, 6, 7, 4, 6, 6, 5, 7, 4, 6,
       5, 7, 5, 7, 6, 5, 6, 5, 5, 6, 6, 7, 5, 7, 5, 5, 6, 5, 6, 6, 6, 7,
       4, 5, 6, 5, 7, 4, 5, 5, 5, 6, 6, 4, 6, 6, 4, 6, 7, 5, 6, 4, 6, 6,
       5, 6, 7, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 6, 6,
       5, 5, 5, 4, 6, 5, 5, 5, 7, 5, 5, 5, 5, 5, 6, 6, 5, 6, 7, 7, 6, 6,
       6, 7, 5, 6, 6, 6, 6, 4, 5, 7, 6, 5, 5, 7, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 5, 5, 6, 6, 6, 6,
       5, 6, 5, 6, 6, 6, 6, 5, 6, 7, 5, 6, 6, 6, 5, 6, 7, 6, 6, 6, 7, 5,
       5])

In [18]:
y_test.values

array([6, 3, 6, 5, 7, 8, 6, 6, 5, 7, 7, 6, 7, 6, 6, 7, 7, 6, 6, 6, 7, 5,
       6, 7, 6, 8, 7, 5, 4, 7, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 7, 6, 6, 6,
       7, 6, 5, 6, 5, 5, 8, 5, 7, 5, 5, 9, 6, 7, 6, 5, 4, 6, 5, 6, 6, 6,
       7, 6, 6, 4, 6, 6, 6, 6, 8, 8, 6, 6, 6, 8, 6, 5, 5, 6, 4, 4, 4, 6,
       5, 7, 5, 6, 6, 7, 6, 6, 6, 3, 7, 4, 6, 6, 6, 6, 6, 4, 6, 6, 7, 6,
       6, 5, 6, 6, 7, 7, 6, 6, 5, 7, 5, 6, 6, 6, 5, 5, 7, 5, 7, 7, 7, 6,
       5, 6, 8, 5, 7, 6, 6, 8, 5, 5, 6, 6, 6, 7, 6, 5, 6, 6, 7, 5, 5, 6,
       6, 5, 6, 6, 5, 4, 5, 6, 6, 6, 7, 4, 5, 5, 6, 7, 6, 6, 6, 5, 6, 5,
       7, 6, 6, 4, 7, 6, 8, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 7, 4, 6,
       6, 6, 5, 4, 7, 5, 6, 6, 5, 6, 6, 6, 5, 6, 7, 6, 4, 6, 6, 6, 5, 6,
       5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 7, 5, 5, 5, 5, 6,
       7, 6, 6, 5, 5, 5, 6, 5, 7, 5, 5, 6, 6, 6, 5, 7, 6, 6, 6, 5, 5, 6,
       7, 6, 6, 6, 5, 7, 6, 6, 6, 7, 5, 5, 6, 7, 6, 6, 7, 7, 7, 6, 5, 6,
       6, 6, 5, 5, 4, 5, 5, 7, 6, 7, 7, 8, 6, 6, 8, 5, 6, 5, 6, 6, 7, 5,
       6, 6, 6, 8, 6, 6, 5, 5, 6, 6, 5, 5, 6, 8, 5, 5, 5, 5, 5, 6, 6, 6,
       6, 4, 7, 6, 7, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 7, 6, 6, 6,
       6, 6, 6, 5, 5, 7, 5, 6, 5, 7, 6, 5, 5, 6, 5, 5, 5, 6, 7, 5, 5, 5,
       7, 6, 7, 5, 6, 5, 5, 6, 6, 5, 8, 6, 7, 7, 5, 4, 6, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 8, 7, 5, 6, 5, 5, 6, 6, 6, 7, 6, 7, 5, 5, 5, 5, 5, 7,
       5, 7, 4, 7, 5, 5, 6, 5, 7, 7, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 7,
       6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 7, 3, 5, 6, 6, 8, 6, 6, 6,
       6, 6, 5, 7, 6, 7, 7, 7, 5, 6, 7, 8, 5, 6, 4, 6, 7, 5, 3, 5, 6, 7,
       5, 4, 5, 6, 6, 6, 7, 5, 7, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6,
       7, 6, 6, 6, 5, 6, 5, 6, 5, 7, 7, 7, 6, 8, 6, 6, 6, 6, 6, 6, 7, 6,
       6, 7, 5, 5, 8, 5, 6, 6, 6, 5, 7, 7, 7, 7, 6, 6, 5, 7, 8, 5, 6, 5,
       6, 5, 6, 5, 5, 6, 6, 6, 4, 8, 5, 7, 4, 6, 7, 6, 6, 7, 6, 6, 5, 6,
       5, 6, 6, 4, 6, 6, 5, 7, 5, 5, 5, 7, 5, 5, 6, 6, 6, 6, 6, 6, 7, 4,
       5, 8, 6, 6, 6, 5, 6, 4, 5, 5, 7, 7, 6, 7, 6, 6, 6, 6, 6, 6, 6, 5,
       6, 5, 8, 5, 6, 6, 6, 4, 6, 5, 6, 5, 4, 7, 7, 4, 7, 5, 5, 6, 5, 6,
       6, 5, 6, 6, 7, 6, 6, 7, 6, 6, 5, 7, 7, 7, 6, 6, 6, 5, 7, 6, 5, 7,
       7, 6, 6, 6, 7, 5, 5, 6, 6, 7, 7, 5, 7, 7, 7, 6, 7, 5, 5, 5, 6, 6,
       5, 6, 6, 5, 6, 6, 4, 6, 8, 6, 6, 5, 7, 6, 7, 6, 5, 7, 5, 6, 7, 6,
       5, 7, 5, 4, 6, 6, 5, 7, 7, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 5, 6, 5,
       5, 7, 5, 6, 5, 7, 6, 7, 6, 6, 6, 7, 6, 6, 6, 7, 5, 7, 5, 7, 8, 6,
       6, 5, 6, 5, 6, 7, 6, 6, 7, 6, 6, 5, 7, 6, 8, 5, 6, 6, 7, 6, 5, 6,
       5, 5, 4, 6, 7, 6, 5, 5, 6, 7, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 5,
       5])

Evaluate your model.

In [19]:
print(f"The accuracy of the model is {knn.score(X_test, y_test)*100: .2f}%")

The accuracy of the model is  41.61%

**Congratulations, you have just developed your first Machine Learning model!**